export {
  BUS_STATUS_COLORS,
  BUS_STATUS_OPTIONS,
  CHART_COLORS,
  DAYS_OF_WEEK_OPTIONS,
  DRIVER_STATUS_COLORS,
  DRIVER_STATUS_OPTIONS,
  FLEET_ROUTES,
  LICENSE_TYPE_OPTIONS,
  ROUTE_STATUS_COLORS,
  ROUTE_STATUS_OPTIONS,
} from './fleet'
